# Available versions : https://gitlab.com/pages/hugo/container_registry
image:
    registry.gitlab.com/pages/hugo/hugo:latest

variables:
    GIT_SUBMODULE_STRATEGY: recursive

pages:
    script:
        - hugo
    artifacts:
        paths:
            - public
    only:
        - master  
