baseurl = "/"
title = "Kodcu"
languageCode = "en-us"
DefaultContentLanguage = "en" # Check i18n folder to see the available languages. You can add you own lang.
paginate = "10" # Number of posts per page
theme = "kodcu"
disqusShortname = "" # Enable comments by entering your Disqus shortname
googleAnalytics = "" # Enable Google Analytics by entering your tracking id
summaryLength = 25

[Author]
  name = "Furkan Tokac"
  bio = "Furkan Tokac's true identity is unknown. Maybe he is a successful blogger or writer. Nobody knows it."
  avatar = "/img/avatar.png"

[Params]
  subtitle = "Just another site" # Subtitle of your site
  description = "ftDev's Personal blog about everything" # Description of your site
  #header_img = "img/placeholder-cropped.png" 
  dateformat = "02.01.2006"
  mainSections = ["post"] # Specify which folders under /content will be shown on the home page
  post_meta = ["date", "categories"] # Posts meta information will be shown below the post title
  images = ["/img/placeholder.png"] # Put default Twitter card images here
  readmore = true # Show "Read more" button in list if true
  authorbox = true # Show author boxes on pages
  post_navigation = true
  lastmod = true
  opengraph = false

[Params.sidebar]
  home = "right"   # Configure layout for home page
  list = "right"   # Configure layout for list pages
  single = "false" # Configure layout for single pages
  # Enable widgets in given order so order matters!
  widgets = ["search", "social", "categories", "recent", "taglist"]

[Params.widgets]
  recent_num = 5 # Set the number of articles in the "Recent articles" widget
  tags_counter = true # Enable counter for each tag in "Tags" widget

[Params.widgets.social]
  # Enable parts of social widget
  twitter = "GoHugoIO"
  instagram = ""
  linkedin = "furkantokac"
  github = "gohugoio"
  gitlab = "furkantokac"
  email = "furkan.tokac[at]kdemail.net"
